# MONGO
spring.data.mongodb.uri=mongodb+srv://Cluster74064:Ql5hbW9gTGBS@cluster74064.jjyyncv.mongodb.net/?retryWrites=true&w=majority
spring.data.mongodb.database=PulseEvent

# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html

#server
server.address=0.0.0.0
server.port=8080

spring.application.name=event-service